# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'L1_KazakovAleksei' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RealmSwift'

  # Pods for L1_KazakovAleksei

  target 'L1_KazakovAlekseiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'L1_KazakovAlekseiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
